# Generated by Django 3.0.7 on 2020-09-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_auto_20200918_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
