# Generated by Django 3.0.7 on 2020-09-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toilet',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cathegory', models.CharField(max_length=120)),
                ('place', models.CharField(max_length=120)),
            ],
        ),
    ]
