# Generated by Django 3.0.7 on 2020-09-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toilet',
            name='cathegory',
        ),
        migrations.AddField(
            model_name='toilet',
            name='category',
            field=models.CharField(choices=[('Restaurant', 'Restaurant'), ('Public', 'Public'), ('Hotel', 'Hotel')], default=None, max_length=120),
        ),
    ]
