# Generated by Django 3.0.7 on 2020-09-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toilet',
            name='overal_design',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='overal_smell',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='overal_space',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='overal_tidiness',
            field=models.FloatField(default=0),
        ),
    ]
