# Generated by Django 3.0.7 on 2020-09-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilet', '0002_auto_20200902_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toilet',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
