# Generated by Django 3.0.7 on 2020-09-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilet', '0003_auto_20200902_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='toilet',
            name='rating',
            field=models.FloatField(default=8),
            preserve_default=False,
        ),
    ]
