# Generated by Django 3.0.7 on 2020-09-10 19:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('toilet', '0004_toilet_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='toilet',
            name='tidiness',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toilet',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
