# Generated by Django 3.0.7 on 2020-09-10 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toilet', '0005_auto_20200910_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toilet',
            name='rating',
        ),
    ]
