# Generated by Django 3.0.7 on 2020-09-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilet', '0006_remove_toilet_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='toilet',
            name='design',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toilet',
            name='smell',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toilet',
            name='space',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
