# Generated by Django 3.0.7 on 2020-09-10 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toilet', '0008_toilet_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toilet',
            name='rating',
        ),
    ]
