# Generated by Django 3.0.7 on 2020-09-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilet', '0009_remove_toilet_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='toilet',
            name='rating',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
