# Generated by Django 3.0.7 on 2020-09-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilet', '0010_toilet_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toilet',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
